name: CI-CD GPH Production Pipeline

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.0.0
        with: 
          context: ./frontends/web
          file: ./frontends/web/Dockerfile
          push: true
          tags: | 
            ldamasio/gph-marketplace:${{github.run_number}}
            ldamasio/gph-marketplace:latest
  CD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Define context
        uses: Azure/k8s-set-context@v3.0
        with: 
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}
          

